spring.application.name=pensionat_kademina

spring.jpa.hibernate.ddl-auto=update

spring.datasource.url=${DATABASE_JDBC_URL}
spring.datasource.username=${MYSQLUSER}
spring.datasource.password=${MYSQLPASSWORD}

customer-service.url=${CUSTOMER_SERVICE_URL}
review-service.url=${REVIEW_SERVICE_URL}
